[package]
name = "pythia"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
duckdb = { version = "0.7.1", features = ["bundled", "modern-full"] }
uuid = { version = "1.3.3", features = ["v4"] }
