[package]
name = "pythia-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.24"
duckdb = { version = "0.7.1", features = ["bundled", "modern-full"] }
pythia-core = { path = "../pythia-core" }
uuid = { version = "1.3.3", features = ["v4"] }
